name: nervouslightning
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31353d'
    - '#ffe36c'
    - '#000000'
    - '#b2a25a'
    - '#897f51'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.5072911765892059
  rhythmicContrast: 0.25
purpose: []
